### ISSUE TITLE
gem sqlite3 version error

### ISSUE THREAD

**Issue by adipasquale** [lewagon/activerecord-sinatra-boilerplate#7]
I haven't digged into it too much but I get an error when running for example `rake db:create`  on a clean gemset with ruby 2.6.5:

```sh
git clone https://github.com/lewagon/activerecord-sinatra-boilerplate.git livecode
cd livecode
rvm gemset create livecode2
rvm gemset use livecode2
gem install bundler
bundle install
rake db:create
```

here is the stack trace i get
```
Gem::MissingSpecVersionError: Could not find 'sqlite3' (~> 1.3.6) - did find: [sqlite3-1.4.1]
Checked in 'GEM_PATH=/Users/adipasquale/.rvm/gems/ruby-2.6.5@livecode5:/Users/adipasquale/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0', execute `gem env` for more information
/Users/adipasquale/.rvm/gems/ruby-2.6.5@livecode5/gems/activerecord-5.1.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:10:in `<top (required)>'
/Users/adipasquale/.rvm/gems/ruby-2.6.5@livecode5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/Users/adipasquale/.rvm/gems/ruby-2.6.5@livecode5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/adipasquale/.rvm/gems/ruby-2.6.5@livecode5/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/adipasquale/.rvm/gems/ruby-2.6.5@livecode5/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:186:in `spec'
/Users/adipasquale/.rvm/gems/ruby-2.6.5@livecode5/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:880:in `establish_connection'
/Users/adipasquale/.rvm/gems/ruby-2.6.5@livecode5/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:58:in `establish_connection'
/Users/adipasquale/dev/lewagon/activerecord-basics/livecode/config/application.rb:9:in `<top (required)>'
/Users/adipasquale/dev/lewagon/activerecord-basics/livecode/Rakefile:4:in `require_relative'
/Users/adipasquale/dev/lewagon/activerecord-basics/livecode/Rakefile:4:in `<top (required)>'
```

can anyone reproduce?

it looked bad during today's livecode 🤦‍♂

**Comment by jadjoubran** [comment]
This worked for me https://stackoverflow.com/a/54580628/1599122
Also during a live code 😅

**Comment by tagspace** [comment]
I have added this pull request (https://github.com/lewagon/activerecord-sinatra-boilerplate/pull/8) which also fixed it for me.
